id: 55bd492d-f204-4916-94e6-d04e96a6a975
name: 'It should work now Lachlan :)'
version: 1.0.0
type: lambda
language: python3.6
code: ''
memory: 768
libraries: []
layers: []
max_execution_time: 900
environment_variables: {}
reserved_concurrency_count: false
tooltip: false
